import { notFound, redirect } from "next/navigation";
import { getPublicSupabaseConfig } from "../../../../src/lib/supabase/config";
import { createClient } from "../../../../src/lib/supabase/server";
import { ApproveChangeset } from "./approve-changeset";
import { ExecuteReferencePortal } from "./execute-reference-portal";

export default async function ReviewChangesetPage({ params }: { params: Promise<{ id: string }> }) {
  if (getPublicSupabaseConfig() === null) redirect("/login");
  const { id } = await params; const supabase = await createClient(); const { data: claims } = await supabase.auth.getClaims();
  if (!claims) redirect(`/login?next=/app/review/${id}`);
  const { data: changeset } = await supabase.from("changesets").select("id, application_id, payload, payload_sha256, state, expires_at, created_at").eq("id", id).maybeSingle();
  if (!changeset) notFound();
  const payload = changeset.payload as { destination?: { origin?: string; path?: string }; actions?: Array<{ kind?: string; expectedObservation?: string; reversible?: boolean }> };
  const isReferencePortal = payload.destination?.origin === "papertrail-reference-portal" && payload.destination?.path === "/reference-portal";
  return <main className="mx-auto min-h-screen w-full max-w-3xl px-5 py-10 sm:px-8"><a className="font-semibold text-[var(--navy)] underline underline-offset-4" href={`/app/applications/${changeset.application_id}`}>Back to application</a><p className="mt-8 text-sm font-semibold uppercase tracking-[0.15em] text-[var(--navy)]">Exact action review</p><h1 className="mt-3 text-4xl font-bold tracking-tight">Review before external action</h1><p className="mt-4 leading-7 text-[var(--slate)]">Approval applies only to this exact envelope. It does not execute any action by itself.</p><section className="mt-8 rounded-xl border border-[var(--border)] bg-white p-6"><h2 className="text-2xl font-bold">Destination</h2><p className="mt-3 break-all font-mono text-sm text-[var(--slate)]">{payload.destination?.origin}{payload.destination?.path}</p>{isReferencePortal ? <p className="mt-3 rounded-md bg-amber-50 p-3 text-sm text-amber-950">This is the built-in fictional reference portal, not an external destination.</p> : null}<h2 className="mt-6 text-2xl font-bold">Planned actions</h2><ul className="mt-3 grid gap-3">{payload.actions?.map((action, index) => <li className="rounded-md bg-slate-50 p-3" key={index}><p className="font-semibold">{action.kind?.replaceAll("_", " ")}</p><p className="mt-1 text-sm text-[var(--slate)]">Expected observation: {action.expectedObservation}</p><p className="mt-1 text-sm text-[var(--slate)]">{action.reversible ? "Reversible action" : "Irreversible action"}</p></li>)}</ul><p className="mt-6 break-all font-mono text-xs text-[var(--slate)]">Payload SHA-256: {changeset.payload_sha256}</p><p className="mt-2 text-sm text-[var(--slate)]">State: {changeset.state.replaceAll("_", " ")} · Expires {new Date(changeset.expires_at).toLocaleString()}</p>{changeset.state === "review_required" ? <ApproveChangeset changesetId={changeset.id} /> : null}{changeset.state === "approved" && isReferencePortal ? <ExecuteReferencePortal changesetId={changeset.id} /> : null}{changeset.state === "approved" && !isReferencePortal ? <p className="mt-5 rounded-md bg-emerald-50 p-3 text-sm text-emerald-900">Approval recorded. Browser execution remains unavailable until a configured provider is connected and the current portal state is inspected again.</p> : null}{changeset.state === "executed" && isReferencePortal ? <p className="mt-5 rounded-md bg-emerald-50 p-3 text-sm text-emerald-900">The fictional portal acknowledgement is recorded. This did not submit to a real institution.</p> : null}</section></main>;
}
