"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { createClient } from "../../../../src/lib/supabase/client";

export function ActivityFollowupControls({ activityId, trackingState }: { activityId: string; trackingState: "active" | "paused" | "ended" }) {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const enabled = trackingState === "active";
  async function toggle(): Promise<void> { setSaving(true); setError(null); const { error: rpcError } = await createClient().rpc("set_activity_followup_opt_in", { p_activity_id: activityId, p_enabled: !enabled }); setSaving(false); if (rpcError) { setError("The follow-up preference could not be saved."); return; } router.refresh(); }
  if (trackingState === "ended") return null;
  return <div className="mt-5 grid gap-2"><button className="min-h-11 justify-self-start rounded-lg border border-[var(--border)] bg-white px-4 py-2 font-semibold text-[var(--navy)] disabled:opacity-60" disabled={saving} onClick={toggle} type="button">{saving ? "Saving…" : enabled ? "Pause follow-up tracking" : "Opt in to follow-up tracking"}</button><p className="text-sm leading-6 text-[var(--slate)]">{enabled ? "Tracking is opted in, but no public source coverage is connected yet. You can record private reminders below." : "Opt in records your consent for this activity. It does not claim that PaperTrail covers an organization or has found an open action."}</p>{error ? <p className="rounded-md bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</p> : null}</div>;
}

export function RecordOwnerFollowupAction({ activityId }: { activityId: string }) {
  const router = useRouter(); const [family, setFamily] = useState(""); const [period, setPeriod] = useState(""); const [kind, setKind] = useState(""); const [deadline, setDeadline] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: React.FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!family.trim() || !period.trim() || !kind.trim()) { setError("Enter a stable action key, period, and action name."); return; } setError(null); setSaving(true); const { error: rpcError } = await createClient().rpc("record_owner_followup_action", { p_activity_id: activityId, p_action_family_key: family.trim(), p_action_period: period.trim(), p_kind: kind.trim(), p_deadline_at: deadline ? new Date(deadline).toISOString() : null, p_deadline_text: null }); setSaving(false); if (rpcError) { setError("The action could not be recorded. Opt in to tracking first and use a lowercase key such as renewal.registration."); return; } setFamily(""); setPeriod(""); setKind(""); setDeadline(""); router.refresh(); }
  return <form className="mt-5 grid gap-3 rounded-xl border border-[var(--border)] bg-white p-5" noValidate onSubmit={submit}><h3 className="font-semibold">Record an owner reminder or next action</h3><p className="text-sm leading-6 text-[var(--slate)]">Use this for a date you know. It is not represented as a verified notice or proof that registration is open.</p><label className="grid gap-1 text-sm font-semibold">Stable action key<input className="min-h-11 rounded-md border border-[var(--border)] px-3" maxLength={120} onChange={(event) => setFamily(event.target.value)} placeholder="renewal.registration" value={family} /></label><label className="grid gap-1 text-sm font-semibold">Period<label className="sr-only" htmlFor="followup-period">Period</label><input className="min-h-11 rounded-md border border-[var(--border)] px-3" id="followup-period" maxLength={120} onChange={(event) => setPeriod(event.target.value)} placeholder="DEMO-2027" value={period} /></label><label className="grid gap-1 text-sm font-semibold">Action<label className="sr-only" htmlFor="followup-kind">Action</label><input className="min-h-11 rounded-md border border-[var(--border)] px-3" id="followup-kind" maxLength={120} onChange={(event) => setKind(event.target.value)} placeholder="Prepare renewal registration" value={kind} /></label><label className="grid gap-1 text-sm font-semibold">Known due date (optional)<input className="min-h-11 rounded-md border border-[var(--border)] px-3" onChange={(event) => setDeadline(event.target.value)} type="datetime-local" value={deadline} /></label>{error ? <p className="rounded-md bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</p> : null}<button className="min-h-11 justify-self-start rounded-lg bg-[var(--navy)] px-4 py-2 font-semibold text-white disabled:opacity-60" disabled={saving} type="submit">{saving ? "Recording…" : "Record private follow-up action"}</button></form>;
}

export function PrepareFollowupApplication({ actionId, defaultTitle }: { actionId: string; defaultTitle: string }) {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function prepare(): Promise<void> { setSaving(true); setError(null); const { data, error: rpcError } = await createClient().rpc("prepare_followup_application", { p_followup_action_id: actionId, p_title: defaultTitle }); setSaving(false); if (rpcError || typeof data !== "string") { setError("A linked draft could not be created for this action."); return; } router.push(`/app/applications/${data}`); router.refresh(); }
  return <div className="mt-3 grid gap-2"><button className="min-h-11 rounded-lg border border-[var(--border)] bg-white px-4 py-2 font-semibold text-[var(--navy)] disabled:opacity-60" disabled={saving} onClick={prepare} type="button">{saving ? "Preparing draft…" : "Prepare linked draft"}</button>{error ? <p className="rounded-md bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</p> : null}</div>;
}
