"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { createClient } from "../../../src/lib/supabase/client";

interface LinkIntent { id: string; state: string; expires_at: string; telegram_username: string | null; }
interface ChannelLink { telegram_username: string | null; unlinked_at: string | null; }

export function TelegramLinkControls({ botUsername, link, pendingIntent }: { botUsername: string | null; link: ChannelLink | null; pendingIntent: LinkIntent | null }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [startToken, setStartToken] = useState<string | null>(null);
  const activeLink = link && link.unlinked_at === null;
  async function createIntent(): Promise<void> { setError(null); setLoading(true); const { data, error: rpcError } = await createClient().rpc("create_telegram_link_intent"); setLoading(false); const row = Array.isArray(data) ? data[0] : data; if (rpcError || !row || typeof row.start_token !== "string") { setError("A secure Telegram link could not be created."); return; } setStartToken(row.start_token); router.refresh(); }
  async function confirm(): Promise<void> { if (!pendingIntent) return; setError(null); setLoading(true); const { error: rpcError } = await createClient().rpc("confirm_telegram_link", { p_intent_id: pendingIntent.id }); setLoading(false); if (rpcError) { setError("The pending chat could not be confirmed. Create a fresh link if it expired."); return; } router.refresh(); }
  async function unlink(): Promise<void> { setError(null); setLoading(true); const { error: rpcError } = await createClient().rpc("unlink_telegram_channel"); setLoading(false); if (rpcError) { setError("The Telegram channel could not be unlinked."); return; } router.refresh(); }
  if (activeLink) return <div className="mt-5 grid gap-3"><p className="rounded-md bg-emerald-50 p-3 text-sm text-emerald-900">Linked private chat{link.telegram_username ? `: @${link.telegram_username}` : ""}. Telegram delivery is not yet claimed as healthy until a real message is observed.</p><button className="min-h-11 justify-self-start rounded-lg border border-[var(--border)] bg-white px-4 py-2 font-semibold text-[var(--navy)] disabled:opacity-60" disabled={loading} onClick={unlink} type="button">{loading ? "Unlinking…" : "Unlink Telegram"}</button></div>;
  return <div className="mt-5 grid gap-3"><p className="text-sm leading-6 text-[var(--slate)]">Create a short-lived link, open it in Telegram, then return here to confirm the exact private chat. Group chats and a username alone can never link to your workspace.</p>{pendingIntent?.state === "awaiting_owner_confirmation" ? <div className="rounded-md bg-amber-50 p-3 text-sm text-amber-950">A private Telegram chat requested linking{pendingIntent.telegram_username ? ` as @${pendingIntent.telegram_username}` : ""}. Confirm only if this is your chat.<button className="ml-3 min-h-11 rounded-lg bg-[var(--navy)] px-4 py-2 font-semibold text-white disabled:opacity-60" disabled={loading} onClick={confirm} type="button">{loading ? "Confirming…" : "Confirm this chat"}</button></div> : null}{startToken ? <div className="rounded-md bg-slate-50 p-4 text-sm text-[var(--slate)]"><p className="font-semibold text-[var(--foreground)]">One-time link created</p>{botUsername ? <a className="mt-2 inline-flex font-semibold text-[var(--navy)] underline underline-offset-4" href={`https://t.me/${botUsername}?start=${startToken}`} rel="noreferrer" target="_blank">Open Telegram and start the bot</a> : <p className="mt-2">Send <code>/start {startToken}</code> to the configured bot within 10 minutes.</p>}</div> : null}<button className="min-h-11 justify-self-start rounded-lg bg-[var(--navy)] px-4 py-2 font-semibold text-white disabled:opacity-60" disabled={loading} onClick={createIntent} type="button">{loading ? "Creating secure link…" : "Link Telegram private chat"}</button>{error ? <p className="rounded-md bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</p> : null}</div>;
}
